import {readBackupSnapshot} from "../lib/backup-snapshot.js";
import {createCipheriv,createDecipheriv,createHash,randomBytes,scryptSync} from "node:crypto";
import {mkdir,readdir,readFile,rename,stat,writeFile} from "node:fs/promises";
import path from "node:path";
import mongoose from "mongoose";
import {connectDb} from "../lib/db.js";
import {AuditLog,Category,Customer,DocumentCounter,Expense,ExpenseCategory,InventoryBatch,Product,Purchase,Sale,Settings,StaffRole,StockTransaction,Supplier,User} from "../models/index.js";
import {getSettings,invalidateSettingsCache} from "./settings.service.js";

const FORMAT="oushadi-pos-backup";
const VERSION=1;
const FILE_PATTERN=/^oushadi-(manual|auto)-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}\.\d{3}Z\.obak$/;
const models={users:User,staffRoles:StaffRole,categories:Category,products:Product,inventoryBatches:InventoryBatch,stockTransactions:StockTransaction,settings:Settings,customers:Customer,sales:Sale,suppliers:Supplier,purchases:Purchase,expenses:Expense,expenseCategories:ExpenseCategory,documentCounters:DocumentCounter,auditLogs:AuditLog};
function nextAutomaticDate(value,frequency){const next=new Date(value);if(frequency==="MONTHLY")next.setUTCMonth(next.getUTCMonth()+1);else next.setUTCDate(next.getUTCDate()+(frequency==="WEEKLY"?7:1));return next;}

function backupDirectory(){return path.resolve(/* turbopackIgnore: true */ process.env.BACKUP_DIR||path.join(process.cwd(),"backups"));}
function encryptionSecret(){return process.env.BACKUP_ENCRYPTION_KEY||"";}
function decryptionSecrets(){return [...new Set([process.env.BACKUP_ENCRYPTION_KEY,process.env.JWT_SECRET].filter(Boolean))];}
function safeName(name){if(!FILE_PATTERN.test(String(name||"")))throw new Error("Invalid backup file");return name;}
function fileName(type,date=new Date()){return `oushadi-${type}-${date.toISOString().replaceAll(":","-")}.obak`;}
function actorId(actor){return actor?.sub||undefined;}
function serializeError(error){return String(error?.message||error).slice(0,500);}

async function ensureDirectory(){const directory=backupDirectory();await mkdir(/* turbopackIgnore: true */ directory,{recursive:true});return directory;}

async function snapshot(){const session=await mongoose.startSession();try{const collections=await readBackupSnapshot(models,session),counts=Object.fromEntries(Object.entries(collections).map(([name,rows])=>[name,rows.length]));const payload={format:FORMAT,version:VERSION,createdAt:new Date().toISOString(),database:collections};const json=JSON.stringify(payload);return{json,counts,checksum:createHash("sha256").update(json).digest("hex")};}finally{await session.endSession();}}

function encrypt(json,metadata){const secret=encryptionSecret();if(!secret)throw new Error("Backup encryption is not configured. Set BACKUP_ENCRYPTION_KEY.");const salt=randomBytes(16),iv=randomBytes(12),key=scryptSync(secret,salt,32),cipher=createCipheriv("aes-256-gcm",key,iv),encrypted=Buffer.concat([cipher.update(json,"utf8"),cipher.final()]);return JSON.stringify({format:FORMAT,version:VERSION,encryption:"AES-256-GCM",createdAt:metadata.createdAt,kind:metadata.kind,checksum:metadata.checksum,salt:salt.toString("base64"),iv:iv.toString("base64"),tag:cipher.getAuthTag().toString("base64"),data:encrypted.toString("base64")});}

function decryptArchive(archive){const secrets=decryptionSecrets();if(!secrets.length)throw new Error("Backup encryption is not configured");if(!Buffer.isBuffer(archive)||archive.length===0)throw new Error("Select a valid backup archive");if(archive.length>100*1024*1024)throw new Error("Backup archive exceeds the 100 MB restore limit");let envelope;try{envelope=JSON.parse(archive.toString("utf8"));}catch{throw new Error("Backup archive is not valid JSON");}if(envelope?.format!==FORMAT||envelope?.version!==VERSION||envelope?.encryption!=="AES-256-GCM")throw new Error("Unsupported backup archive format");const salt=Buffer.from(envelope.salt,"base64"),iv=Buffer.from(envelope.iv,"base64"),tag=Buffer.from(envelope.tag,"base64"),encrypted=Buffer.from(envelope.data,"base64");let json="";for(const secret of secrets){try{const key=scryptSync(secret,salt,32),decipher=createDecipheriv("aes-256-gcm",key,iv);decipher.setAuthTag(tag);json=Buffer.concat([decipher.update(encrypted),decipher.final()]).toString("utf8");break;}catch{}}if(!json)throw new Error("Backup could not be decrypted. The archive or encryption key is invalid.");if(createHash("sha256").update(json).digest("hex")!==envelope.checksum)throw new Error("Backup integrity check failed");let payload;try{payload=JSON.parse(json);}catch{throw new Error("Decrypted backup data is invalid");}if(payload?.format!==FORMAT||payload?.version!==VERSION||!payload.database)throw new Error("Backup payload is unsupported");for(const name of Object.keys(models))if(!Array.isArray(payload.database[name]))throw new Error(`Backup collection ${name} is missing`);if(!payload.database.users.some((user)=>user.role==="ADMIN"&&user.active!==false))throw new Error("Backup must contain an active owner account");return payload;}

export function inspectBackup(archive){const payload=decryptArchive(archive);return{createdAt:payload.createdAt,counts:Object.fromEntries(Object.entries(payload.database).map(([name,rows])=>[name,rows.length]))};}

async function audit(action,description,metadata,actor){await AuditLog.create({actorId:actorId(actor),action,module:"backup",targetType:"Backup",description,metadata});}

export async function listBackups(){const directory=await ensureDirectory(),names=(await readdir(/* turbopackIgnore: true */ directory)).filter((name)=>FILE_PATTERN.test(name));const rows=await Promise.all(names.map(async(name)=>{const info=await stat(/* turbopackIgnore: true */ path.join(directory,name));return{name,type:name.startsWith("oushadi-auto-")?"AUTOMATIC":"MANUAL",createdAt:info.mtime.toISOString(),size:info.size};}));return rows.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));}

export async function createBackup({type="manual",actor}={}){if(!["manual","auto"].includes(type))throw new Error("Invalid backup type");await connectDb();const startedAt=new Date(),{json,counts,checksum}=await snapshot(),name=fileName(type,startedAt),directory=await ensureDirectory(),target=path.join(directory,name),temporary=`${target}.${randomBytes(6).toString("hex")}.tmp`,archive=encrypt(json,{createdAt:startedAt.toISOString(),kind:type.toUpperCase(),checksum});await writeFile(temporary,archive,{encoding:"utf8",flag:"wx"});await rename(temporary,target);const info=await stat(target);await audit("BACKUP_CREATED",`${type==="auto"?"Automatic":"Manual"} encrypted backup created`,{name,type,size:info.size,counts,checksum},actor);return{name,type:type.toUpperCase(),createdAt:startedAt.toISOString(),size:info.size,counts};}

export async function readBackup(name){const file=safeName(name);return readFile(/* turbopackIgnore: true */ path.join(await ensureDirectory(),file));}

export async function restoreBackup(archive,actor){if(global.oushadiRestoreInProgress)throw new Error("Another database restore is already running");global.oushadiRestoreInProgress=true;let session;try{await connectDb();const payload=decryptArchive(archive),safetyBackup=await createBackup({type:"manual",actor});session=await mongoose.startSession();await session.withTransaction(async()=>{for(const Model of Object.values(models))await Model.deleteMany({}).session(session);for(const[name,Model]of Object.entries(models)){const rows=payload.database[name];if(rows.length)await Model.insertMany(rows,{session,ordered:true});}await AuditLog.create([{actorId:actorId(actor),action:"BACKUP_RESTORED",module:"backup",targetType:"Backup",description:"Database restored from encrypted backup",metadata:{sourceCreatedAt:payload.createdAt,safetyBackup:safetyBackup.name}}],{session});},{readConcern:{level:"snapshot"},writeConcern:{w:"majority"}});invalidateSettingsCache();return{restored:true,sourceCreatedAt:payload.createdAt,safetyBackup:safetyBackup.name,counts:Object.fromEntries(Object.entries(payload.database).map(([name,rows])=>[name,rows.length]))};}finally{global.oushadiRestoreInProgress=false;if(session)await session.endSession();}}

export async function getBackupStatus({runDue=true}={}){if(runDue)await runDueAutomaticBackup();const settings=await getSettings(),backups=await listBackups(),automatic=backups.filter((item)=>item.type==="AUTOMATIC"),last=backups[0]||null,lastAutomatic=automatic[0]||null,frequency=settings.backup.frequency;return{configured:Boolean(encryptionSecret()),keySource:process.env.BACKUP_ENCRYPTION_KEY?"BACKUP_ENCRYPTION_KEY":null,directory:backupDirectory(),automaticEnabled:settings.backup.automaticEnabled,frequency,lastBackup:last,lastAutomaticBackup:lastAutomatic,nextAutomaticAt:settings.backup.automaticEnabled?(lastAutomatic?nextAutomaticDate(lastAutomatic.createdAt,frequency):new Date()).toISOString():null,backups};}

let automaticRun=global.oushadiAutomaticBackupRun||null;
export async function runDueAutomaticBackup(){if(global.oushadiRestoreInProgress)return null;if(automaticRun)return automaticRun;automaticRun=(async()=>{try{await connectDb();const settings=await getSettings();if(!settings.backup.automaticEnabled||!encryptionSecret())return null;const automatic=(await listBackups()).filter((item)=>item.type==="AUTOMATIC"),last=automatic[0];if(last&&Date.now()<nextAutomaticDate(last.createdAt,settings.backup.frequency).getTime())return null;return await createBackup({type:"auto"});}catch(error){try{await connectDb();await audit("BACKUP_FAILED","Automatic backup failed",{error:serializeError(error)});}catch{}return null;}finally{automaticRun=null;global.oushadiAutomaticBackupRun=null;}})();global.oushadiAutomaticBackupRun=automaticRun;return automaticRun;}

export function startBackupScheduler(){if(process.env.BACKUP_SCHEDULER_ENABLED==="false"||global.oushadiBackupTimer)return;const check=()=>runDueAutomaticBackup().catch(()=>{});const first=setTimeout(check,10000);first.unref?.();const timer=setInterval(check,15*60*1000);timer.unref?.();global.oushadiBackupTimer=timer;}
