import {Customer} from "@/models";

const clean=(value)=>String(value||"").trim();
export const normalizePhone=(value)=>{const digits=clean(value).replace(/\D/g,"");if(!digits)return"";if(digits.length>10&&(digits.startsWith("91")||digits.startsWith("0")))return digits.slice(-10);return digits};
export const normalizeEmail=(value)=>clean(value).toLowerCase();
export const escapeRegex=(value)=>String(value).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const legacyPhonePattern=(digits)=>String(digits).split("").map(escapeRegex).join("\\D*");
export function customerFields(body={}){const phone=clean(body.phone),status=body.status==="INACTIVE"?"INACTIVE":"ACTIVE",customerType=body.customerType==="WHOLESALE"?"WHOLESALE":"RETAIL",gstin=clean(body.gstin).toUpperCase();if(gstin&&!/^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z\d]Z[A-Z\d]$/.test(gstin))throw new Error("Enter a valid GSTIN");return{name:clean(body.name),phone,normalizedPhone:normalizePhone(phone),email:normalizeEmail(body.email),address:clean(body.address),customerType,businessName:clean(body.businessName),gstin,billingAddress:clean(body.billingAddress||body.address),shippingAddress:clean(body.shippingAddress),creditLimit:Math.max(0,Number(body.creditLimit||0)),outstandingAmount:Math.max(0,Number(body.outstandingAmount||0)),defaultDiscount:Math.min(100,Math.max(0,Number(body.defaultDiscount||0))),notes:clean(body.notes),status,active:status==="ACTIVE"}}
export async function searchCustomers(query,limit=10,{includeInactive=false,customerType}={}){const q=clean(query);if(q.length<2)return[];const safe=escapeRegex(q),phone=normalizePhone(q),filter={};if(!includeInactive)filter.$and=[{$or:[{status:"ACTIVE"},{status:{$exists:false},active:{$ne:false}}]}];if(customerType==="WHOLESALE")filter.customerType="WHOLESALE";if(customerType==="RETAIL")filter.$and=[...(filter.$and||[]),{$or:[{customerType:"RETAIL"},{customerType:{$exists:false}}]}];filter.$or=[{name:{$regex:safe,$options:"i"}},{businessName:{$regex:safe,$options:"i"}},{gstin:{$regex:safe,$options:"i"}},{phone:{$regex:safe,$options:"i"}},{email:{$regex:safe,$options:"i"}}];if(phone.length>=4)filter.$or.push({normalizedPhone:{$regex:`${escapeRegex(phone)}$`}},{phone:{$regex:`${legacyPhonePattern(phone)}$`}});return Customer.find(filter).select("name phone normalizedPhone email address customerType businessName gstin billingAddress shippingAddress creditLimit outstandingAmount defaultDiscount notes status active createdAt").sort({updatedAt:-1}).limit(Math.min(Number(limit)||10,50)).lean()}
export async function findDuplicateCustomer({normalizedPhone,phone,email},session,excludeId){const clauses=[],normalized=normalizedPhone||normalizePhone(phone),normalizedEmail=normalizeEmail(email);if(normalized)clauses.push({$or:[{normalizedPhone:normalized},{normalizedPhone:{$in:[null,""]},phone:{$regex:`${legacyPhonePattern(normalized)}$`}}]});if(normalizedEmail)clauses.push({email:normalizedEmail});if(!clauses.length)return null;const query=Customer.findOne({...(excludeId?{_id:{$ne:excludeId}}:{}),$or:clauses});if(session)query.session(session);return query.lean()}
export async function createCustomer(data,session){const fields=customerFields(data);if(!fields.name)throw new Error("Customer name is required");if(fields.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fields.email))throw new Error("Enter a valid email address");if(fields.phone&&fields.normalizedPhone.length<7)throw new Error("Enter a valid phone number");const duplicate=await findDuplicateCustomer(fields,session);if(duplicate){const error=new Error(`${fields.normalizedPhone&&normalizePhone(duplicate.phone)===fields.normalizedPhone?"Phone number":"Email"} already belongs to ${duplicate.name}`);error.code="DUPLICATE_CUSTOMER";error.customer=duplicate;throw error}const[customer]=await Customer.create([fields],{session,ordered:true});return customer}
