export function isCountBasedProduct(product){return product?.loosePricingMethod==="count_based";}
export function getLooseUnit(product){return isCountBasedProduct(product)?product.looseUnit||"tablet":product.baseUnit;}
export function calculatePhysicalStock(batches=[],product){const stock=batches.reduce((s,b)=>({sealedPackages:s.sealedPackages+Number(b.sealedPackages||0),openQuantity:s.openQuantity+Number(b.openQuantity||0),totalBaseQuantity:s.totalBaseQuantity+Number(b.sealedPackages||0)*Number(b.packageSize||0)+Number(b.openQuantity||0)}),{sealedPackages:0,openQuantity:0,totalBaseQuantity:0});stock.hasStock=stock.sealedPackages>0||stock.openQuantity>0;if(isCountBasedProduct(product)){stock.totalLooseQuantity=stock.openQuantity+(product.looseConversionType==="fixed"?stock.sealedPackages*Number(product.unitsPerPackage||0):0);stock.totalBaseQuantity=stock.openQuantity;}return stock;}
export function packageEquivalentStock(stock,product){if(isCountBasedProduct(product))return Number(stock.sealedPackages||0);const packageSize=Number(product?.packageSize||0);return Number(stock.sealedPackages||0)+(packageSize>0?Number(stock.openQuantity||0)/packageSize:0);}
export function isLowStock(stock,product){return Number(product?.reorderLevel||0)>0&&packageEquivalentStock(stock,product)<=Number(product.reorderLevel);}
function formatSealedStock(count,product){const units=Number(product?.unitsPerStockPack||1),packType=product?.stockPackType||"Box",packageType=product?.packageType||"Package",packPlural=packType==="Box"?"Boxes":`${packType}s`;if(!Number.isInteger(units)||units<=1)return `${count} ${packageType}${count===1?"":"s"}`;const fullPacks=Math.floor(count/units),remainder=count%units,parts=[];if(fullPacks)parts.push(`${fullPacks} ${fullPacks===1?packType:packPlural}`);if(remainder)parts.push(`${remainder} ${packageType}${remainder===1?"":"s"}`);return parts.length?parts.join(" + "):`0 ${packPlural}`;}
export function formatPhysicalStock(stock,product){const count=stock.sealedPackages;const sealed=formatSealedStock(count,product);const unit=getLooseUnit(product);if(isCountBasedProduct(product)){const loose=Number(stock.openQuantity||0);if(!count)return loose?`${loose} ${unit}${loose===1?"":"s"}`:sealed;if(!loose)return sealed;return `${sealed} + ${loose} ${unit}${loose===1?"":"s"}`;}const open=stock.openQuantity>0?` + ${stock.openQuantity} ${product.baseUnit} Open`:"";return `${sealed}${open}`;}
export function deductLooseStock(batch,quantity){const requested=Number(quantity);if(!(requested>0))throw new Error("Quantity must be greater than zero");const packageSize=Number(batch.packageSize);let sealedPackages=Number(batch.sealedPackages);let openQuantity=Number(batch.openQuantity);if(openQuantity<requested){const packagesToOpen=Math.ceil((requested-openQuantity)/packageSize);if(sealedPackages<packagesToOpen)throw new Error("Insufficient stock");sealedPackages-=packagesToOpen;openQuantity+=packagesToOpen*packageSize;}openQuantity-=requested;return{sealedPackages,openQuantity};}
export function deductPackageStock(batch,quantity){const requested=Number(quantity);if(!Number.isInteger(requested)||requested<=0)throw new Error("Package quantity must be a positive integer");if(Number(batch.sealedPackages)<requested)throw new Error("Insufficient sealed package stock");return{sealedPackages:Number(batch.sealedPackages)-requested,openQuantity:Number(batch.openQuantity)};}
export function deductCountBasedLooseStock(batch,quantity,product,openPackageCounts=[]){const requested=Number(quantity);if(!Number.isInteger(requested)||requested<=0)throw new Error(`${getLooseUnit(product)} quantity must be a positive whole number`);let sealedPackages=Number(batch.sealedPackages||0),openQuantity=Number(batch.openQuantity||0);const openings=[];while(openQuantity<requested){if(sealedPackages<=0)throw new Error(`No sealed ${product.packageType}s are available to open.`);let count;if(product.looseConversionType==="fixed")count=Number(product.unitsPerPackage);else count=Number(openPackageCounts[openings.length]);if(!Number.isInteger(count)||count<=0)throw new Error(`Enter the number of ${getLooseUnit(product)}s in this ${product.packageType}.`);sealedPackages-=1;openQuantity+=count;openings.push(count);}openQuantity-=requested;return{sealedPackages,openQuantity,openings};}
