import test from "node:test";
import assert from "node:assert/strict";
import { buildAccountLedger } from "../src/services/accounting.service.js";

test("accounts include sale receipts and purchase-linked expenses once", () => { const result = buildAccountLedger([{ _id:"s1", invoiceNumber:"INV-1", total:500, createdAt:"2026-08-15", customerSnapshot:{name:"Customer"}, payments:[{method:"CASH",amount:500,paidAt:"2026-08-15"}] }], [{ _id:"e1", source:"PURCHASE", category:"Purchase", description:"Inventory purchase PUR-1", amount:200, paymentMethod:"CASH", expenseDate:"2026-08-15" }],{enabledMethods:["CASH"]}); assert.equal(result.summary.moneyIn,500);assert.equal(result.summary.moneyOut,200);assert.equal(result.summary.netCashFlow,300);assert.equal(result.movements.length,2); });
test("sale payments are capped at the bill total", () => { const result=buildAccountLedger([{_id:"s",invoiceNumber:"INV",total:100,createdAt:"2026-08-15",payments:[{method:"UPI",amount:80},{method:"UPI",amount:80}]}],[]); assert.equal(result.summary.moneyIn,100); });
test("wholesale credit invoices do not create cash movements before payment",()=>{const result=buildAccountLedger([{_id:"credit-1",invoiceNumber:"WSI-1",total:500,paymentStatus:"UNPAID",amountPaid:0,balanceDue:500,payments:[]}],[]);assert.equal(result.summary.moneyIn,0);assert.equal(result.movements.length,0);});
test("accounts use only the paid portion of a supplier purchase",()=>{const result=buildAccountLedger([], [{_id:"p1",source:"PURCHASE",description:"Inventory purchase PUR-20260817-001",amount:15000,paidAmount:10000,balanceDue:5000,paymentMethod:"BANK",expenseDate:"2026-08-17"}]);assert.equal(result.summary.moneyOut,10000);assert.equal(result.movements[0].amount,10000);});
test("void expenses remain auditable but are excluded from Accounts",()=>{const result=buildAccountLedger([], [{_id:"e1",expenseNumber:"EXP-20260817-001",title:"Electricity bill",source:"MANUAL",status:"VOID",amount:3200,paymentMethod:"UPI",expenseDate:"2026-08-17"}]);assert.equal(result.summary.moneyOut,0);assert.equal(result.movements.length,0);});
test("manual expense movements use their stable expense number and title",()=>{const result=buildAccountLedger([], [{_id:"e2",expenseNumber:"EXP-20260817-002",title:"Internet bill",category:"Internet",source:"MANUAL",status:"ACTIVE",amount:1500,paymentMethod:"BANK",expenseDate:"2026-08-17"}]);assert.equal(result.movements[0].reference,"EXP-20260817-002");assert.equal(result.movements[0].description,"Internet bill");});
test("split sale payments stay one transaction with channel-level reconciliation",()=>{const paidAt="2026-08-15T18:11:39.000Z";const result=buildAccountLedger([{_id:"s1",invoiceNumber:"INV-1",total:500,customerSnapshot:{name:"Customer"},payments:[{method:"CASH",amount:200,paidAt},{method:"UPI",amount:300,paidAt}]}],[],{enabledMethods:["CASH","UPI"]});assert.equal(result.movements.length,1);assert.equal(result.movements[0].method,"CASH + UPI");assert.deepEqual(result.movements[0].paymentBreakdown.map(({method,amount})=>({method,amount})),[{method:"CASH",amount:200},{method:"UPI",amount:300}]);assert.equal(result.paymentMethods.find((entry)=>entry.method==="CASH").moneyIn,200);assert.equal(result.paymentMethods.find((entry)=>entry.method==="UPI").moneyIn,300);});
test("running balances remain chronological when rows are newest first",()=>{const result=buildAccountLedger([{_id:"s1",invoiceNumber:"INV-1",total:100,createdAt:"2026-08-15",payments:[{method:"CASH",amount:100,paidAt:"2026-08-15"}]}],[{_id:"e1",expenseNumber:"EXP-1",source:"MANUAL",status:"ACTIVE",category:"Utilities",amount:30,paymentMethod:"CASH",expenseDate:"2026-08-16"}],{order:"desc",enabledMethods:["CASH"]});assert.equal(result.movements[0].reference,"EXP-1");assert.equal(result.movements[0].runningBalance,70);assert.equal(result.movements[1].runningBalance,100);});
test("server filters and pagination do not change ledger balances",()=>{const sales=[1,2,3].map((value)=>({_id:`s${value}`,invoiceNumber:`INV-${value}`,total:value*100,createdAt:`2026-08-0${value}`,customerSnapshot:{name:value===2?"David":"Walk-in Customer"},payments:[{method:"CASH",amount:value*100,paidAt:`2026-08-0${value}`}]}));const result=buildAccountLedger(sales,[],{search:"David",page:1,limit:1});assert.equal(result.pagination.total,1);assert.equal(result.movements[0].reference,"INV-2");assert.equal(result.movements[0].runningBalance,300);});
test("cash-flow chart groups transaction days in the store timezone",()=>{const result=buildAccountLedger([{_id:"s1",invoiceNumber:"INV-1",total:100,payments:[{method:"CASH",amount:100,paidAt:"2026-08-16T19:00:00.000Z"}]}],[]);assert.equal(result.cashFlow[0].date,"2026-08-17");});
test("account filters accept multiple transaction types and payment methods",()=>{const sales=[{_id:"s1",invoiceNumber:"INV-1",total:100,payments:[{method:"CASH",amount:100,paidAt:"2026-08-16"}]},{_id:"s2",invoiceNumber:"INV-2",total:200,payments:[{method:"UPI",amount:200,paidAt:"2026-08-16"}]}],expenses=[{_id:"e1",expenseNumber:"EXP-1",source:"MANUAL",status:"ACTIVE",amount:50,paymentMethod:"BANK",expenseDate:"2026-08-16"}],result=buildAccountLedger(sales,expenses,{transactionType:["SALE","EXPENSE"],paymentMethod:["CASH","BANK"]});assert.deepEqual(result.movements.map((row)=>row.reference).sort(),["EXP-1","INV-1"]);});
