import { Customer, Expense, InventoryBatch, Product, Purchase, Sale, Supplier, User } from "@/models";
import { summarizeWholesaleSales } from "@/lib/wholesale-reporting";

const amount=(value)=>Number(Number(value||0).toFixed(2));
const startOfDay=(value)=>{const date=new Date(value);date.setHours(0,0,0,0);return date;};
const endOfDay=(value)=>{const date=new Date(value);date.setHours(23,59,59,999);return date;};
function rangeDates(range="today") { const now=new Date(),end=endOfDay(now),start=startOfDay(now); if(range==="yesterday"){start.setDate(start.getDate()-1);end.setDate(end.getDate()-1);} if(range==="7d")start.setDate(start.getDate()-6); if(range==="week"){const day=(start.getDay()+6)%7;start.setDate(start.getDate()-day);} if(range==="month")start.setDate(1); const duration=end-start+1; return{start,end,previousStart:new Date(start.getTime()-duration),previousEnd:new Date(start.getTime()-1)}; }
const inRange=(value,start,end)=>{const date=new Date(value);return date>=start&&date<=end;};
function comparison(current,previous){if(!previous)return null;return amount(((current-previous)/previous)*100);}

export async function getDashboardData(range="today") {
  const dates=rangeDates(range);
  const [sales,expenses,purchases,products,batches,customerCount,supplierCount,staffCount]=await Promise.all([
    Sale.find({createdAt:{$gte:dates.previousStart,$lte:dates.end}}).lean(),Expense.find({expenseDate:{$gte:dates.previousStart,$lte:dates.end}}).lean(),Purchase.find({purchasedAt:{$gte:dates.previousStart,$lte:dates.end}}).populate("supplierId","name").lean(),Product.find({active:true}).populate("categoryId","name").lean(),InventoryBatch.find().populate("productId","name baseUnit packageType packageSize reorderLevel categoryId").lean(),Customer.countDocuments({active:{$ne:false}}),Supplier.countDocuments({active:{$ne:false}}),User.countDocuments({active:true})]);
  const currentSales=sales.filter((sale)=>inRange(sale.createdAt,dates.start,dates.end)),previousSales=sales.filter((sale)=>inRange(sale.createdAt,dates.previousStart,dates.previousEnd));
  const currentExpenses=expenses.filter((entry)=>inRange(entry.expenseDate,dates.start,dates.end)),previousExpenses=expenses.filter((entry)=>inRange(entry.expenseDate,dates.previousStart,dates.previousEnd));
  const productById=new Map(products.map((product)=>[String(product._id),product]));
  const batchByProduct=new Map();for(const batch of batches){const id=String(batch.productId?._id||batch.productId);if(!batchByProduct.has(id))batchByProduct.set(id,[]);batchByProduct.get(id).push(batch);}
  const unitCost=new Map();let inventoryValue=0;for(const product of products){const rows=batchByProduct.get(String(product._id))||[];let base=0,cost=0;for(const batch of rows){const qty=Number(batch.sealedPackages||0)*Number(batch.packageSize||product.packageSize)+Number(batch.openQuantity||0);base+=qty;const perBase=Number(batch.purchasePrice||0)/Number(batch.packageSize||product.packageSize||1);cost+=qty*perBase;inventoryValue+=qty*perBase;}unitCost.set(String(product._id),base?cost/base:0);}
  function saleCost(sale){let cost=0;for(const item of sale.items||[]){if(item.kind==="MIX"){for(const ingredient of item.ingredients||[])cost+=Number(ingredient.baseQuantity||0)*Number(unitCost.get(String(ingredient.productId))||0);continue;}const productId=String(item.productId),product=productById.get(productId);cost+=Number(item.baseQuantity||0)*Number(unitCost.get(productId)||0);if(item.saleMode==="WHOLESALE"&&Number(item.freeQuantity)>0){const freeProductId=String(item.freeProductId||productId),freeProduct=productById.get(freeProductId);cost+=Number(item.freeQuantity)*Number(freeProduct?.packageSize||product?.packageSize||0)*Number(unitCost.get(freeProductId)||0);}}return amount(cost);}
  const salesTotal=(rows)=>amount(rows.reduce((sum,sale)=>sum+Number(sale.total||0),0)),profitTotal=(rows)=>amount(rows.reduce((sum,sale)=>sum+Number(sale.total||0)-saleCost(sale),0)),expenseTotal=(rows)=>amount(rows.reduce((sum,entry)=>sum+Number(entry.amount||0),0));
  const currentRevenue=salesTotal(currentSales),previousRevenue=salesTotal(previousSales),currentProfit=profitTotal(currentSales),previousProfit=profitTotal(previousSales);
  const wholesale=summarizeWholesaleSales(currentSales);
  const stockByProduct=new Map();for(const product of products){const rows=batchByProduct.get(String(product._id))||[];stockByProduct.set(String(product._id),rows.reduce((sum,batch)=>sum+Number(batch.sealedPackages||0)*Number(batch.packageSize||product.packageSize)+Number(batch.openQuantity||0),0));}
  const lowStockAll=products.filter((product)=>Number(product.reorderLevel)>0&&Number(stockByProduct.get(String(product._id))||0)<=Number(product.reorderLevel)).map((product)=>({id:product._id,name:product.name,unit:product.baseUnit,current:amount(stockByProduct.get(String(product._id))),reorder:Number(product.reorderLevel)})).sort((a,b)=>a.current/a.reorder-b.current/b.reorder);
  const lowStock=lowStockAll.slice(0,5);
  const now=new Date(),expiryLimit=new Date(now);expiryLimit.setDate(expiryLimit.getDate()+60);const expiringAll=batches.filter((batch)=>batch.expiryDate&&new Date(batch.expiryDate)>=startOfDay(now)&&new Date(batch.expiryDate)<=expiryLimit&&(Number(batch.sealedPackages)>0||Number(batch.openQuantity)>0)).map((batch)=>({id:batch._id,product:batch.productId?.name||"Product",batch:batch.batchNumber,expiryDate:batch.expiryDate,days:Math.ceil((new Date(batch.expiryDate)-startOfDay(now))/86400000)})).sort((a,b)=>a.days-b.days);
  const expiring=expiringAll.slice(0,5);
  const opened=batches.filter((batch)=>Number(batch.openQuantity)>0).map((batch)=>({id:batch._id,product:batch.productId?.name||"Product",batch:batch.batchNumber,sealed:Number(batch.sealedPackages||0),open:Number(batch.openQuantity),unit:batch.productId?.baseUnit,packageType:batch.productId?.packageType,updatedAt:batch.updatedAt})).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,5);
  const inventoryGroups={ml:0,g:0,tablets:0,pcs:0};for(const product of products)inventoryGroups[product.baseUnit]=amount((inventoryGroups[product.baseUnit]||0)+Number(stockByProduct.get(String(product._id))||0));
  const productSales=new Map(),categorySales=new Map(),loose={count:0,revenue:0,quantities:{ml:0,g:0,tablets:0,pcs:0}},mixtures={count:0,revenue:0,items:new Map()};
  for(const sale of currentSales)for(const item of sale.items||[]){if(item.kind==="MIX"){mixtures.count+=Number(item.quantity||1);mixtures.revenue+=Number(item.total||0);const key=item.name||"Custom mix",current=mixtures.items.get(key)||{name:key,sales:0,revenue:0};current.sales+=Number(item.quantity||1);current.revenue+=Number(item.total||0);mixtures.items.set(key,current);continue;}const product=productById.get(String(item.productId));const key=String(item.productId),current=productSales.get(key)||{id:item.productId,name:item.name,category:product?.categoryId?.name||"Uncategorized",quantity:0,revenue:0,unit:product?.baseUnit};current.quantity+=Number(item.quantity||0);current.revenue+=Number(item.total||0);productSales.set(key,current);categorySales.set(current.category,(categorySales.get(current.category)||0)+Number(item.total||0));if(item.saleMode==="LOOSE"){loose.count++;loose.revenue+=Number(item.total||0);loose.quantities[product?.baseUnit]=amount((loose.quantities[product?.baseUnit]||0)+Number(item.baseQuantity||0));}}
  const payments=new Map();for(const sale of currentSales)for(const payment of sale.payments||[])payments.set(payment.method,(payments.get(payment.method)||0)+Number(payment.amount||0));const paymentTotal=[...payments.values()].reduce((sum,value)=>sum+value,0);
  const chart=[];for(let offset=6;offset>=0;offset--){const day=startOfDay(dates.end);day.setDate(day.getDate()-offset);const dayEnd=endOfDay(day),previousDay=new Date(day);previousDay.setDate(previousDay.getDate()-7);const previousDayEnd=endOfDay(previousDay);const daySales=sales.filter((sale)=>inRange(sale.createdAt,day,dayEnd)),previousDaySales=sales.filter((sale)=>inRange(sale.createdAt,previousDay,previousDayEnd));chart.push({label:new Intl.DateTimeFormat("en-IN",{weekday:"short"}).format(day),date:day.toISOString(),sales:salesTotal(daySales),previous:salesTotal(previousDaySales),orders:daySales.length,profit:profitTotal(daySales)});}
  const currentPurchases=purchases.filter((purchase)=>inRange(purchase.purchasedAt,dates.start,dates.end));const purchaseTotal=amount(currentPurchases.reduce((sum,purchase)=>sum+Number(purchase.total||0),0));
  const paymentBreakdown=[...payments.entries()].map(([method,value])=>({method,amount:amount(value),percent:paymentTotal?amount(value/paymentTotal*100):0}));
  const expiringSoonCount=expiringAll.filter((item)=>item.days<=30).length;
  return{range,rangeLabel:{today:"Today",yesterday:"Yesterday","7d":"Last 7 Days",week:"This Week",month:"This Month"}[range]||"Today",generatedAt:new Date(),kpis:{sales:currentRevenue,orders:currentSales.length,profit:currentProfit,transactions:currentSales.reduce((sum,sale)=>sum+(sale.payments?.length||0),0),lowStock:lowStockAll.length,comparisons:{sales:comparison(currentRevenue,previousRevenue),orders:comparison(currentSales.length,previousSales.length),profit:comparison(currentProfit,previousProfit),transactions:comparison(currentSales.reduce((sum,sale)=>sum+(sale.payments?.length||0),0),previousSales.reduce((sum,sale)=>sum+(sale.payments?.length||0),0))}},salesOverview:{current:currentRevenue,previous:previousRevenue,chart},topProducts:[...productSales.values()].sort((a,b)=>b.revenue-a.revenue).slice(0,5),recentTransactions:[...currentSales].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,6),inventory:{groups:inventoryGroups,value:amount(inventoryValue)},expiring,lowStock,opened,loose:{count:loose.count,revenue:amount(loose.revenue),quantities:loose.quantities},mixtures:{count:mixtures.count,revenue:amount(mixtures.revenue),items:[...mixtures.items.values()].sort((a,b)=>b.sales-a.sales).slice(0,4)},wholesale:{...wholesale,products:wholesale.products.slice(0,4)},payments:paymentBreakdown,financial:{sales:currentRevenue,expenses:expenseTotal(currentExpenses),profit:currentProfit,netMovement:amount(currentRevenue-expenseTotal(currentExpenses)),previousExpenses:expenseTotal(previousExpenses)},purchases:{total:purchaseTotal,count:currentPurchases.length,latest:[...purchases].sort((a,b)=>new Date(b.purchasedAt)-new Date(a.purchasedAt))[0]||null},suppliers:{active:supplierCount},categories:[...categorySales.entries()].map(([name,value])=>({name,value:amount(value),percent:currentRevenue?amount(value/currentRevenue*100):0})).sort((a,b)=>b.value-a.value).slice(0,5),totals:{products:products.length,customers:customerCount,suppliers:supplierCount,staff:staffCount,inventoryValue:amount(inventoryValue)},notifications:{count:lowStockAll.length+expiringSoonCount+opened.length,lowStock:lowStockAll.length,expiring:expiringSoonCount,opened:opened.length}};
}
