import mongoose from "mongoose";
const {Schema}=mongoose;
const model=(name,schema)=>mongoose.models[name]||mongoose.model(name,schema);
const userSchema=new Schema({name:{type:String,required:true,trim:true},email:{type:String,required:true,unique:true,lowercase:true,trim:true},phone:{type:String,trim:true,default:""},passwordHash:{type:String,required:true},role:{type:String,enum:["ADMIN","STAFF"],default:"STAFF"},bootstrapKey:{type:String,unique:true,sparse:true,immutable:true},roleId:{type:Schema.Types.ObjectId,ref:"StaffRole",index:true},permissions:[String],permissionOverrides:{type:Schema.Types.Mixed,default:{}},active:{type:Boolean,default:true,index:true},mustChangePassword:{type:Boolean,default:false},authVersion:{type:Number,default:0,min:0},readNotificationIds:{type:[String],default:[]},dismissedNotificationIds:{type:[String],default:[]},lastLoginAt:Date,lastActiveAt:Date,createdBy:{type:Schema.Types.ObjectId,ref:"User"},deactivatedAt:Date,deactivatedBy:{type:Schema.Types.ObjectId,ref:"User"},deactivationReason:{type:String,trim:true,default:""}},{timestamps:true});
const staffRoleSchema=new Schema({name:{type:String,required:true,unique:true,trim:true},slug:{type:String,required:true,unique:true,trim:true,index:true},description:{type:String,trim:true,default:""},systemRole:{type:Boolean,default:false},permissionVersion:{type:Number,default:0},permissions:{type:Schema.Types.Mixed,default:{}},active:{type:Boolean,default:true,index:true},createdBy:{type:Schema.Types.ObjectId,ref:"User"}},{timestamps:true});
const auditLogSchema=new Schema({actorId:{type:Schema.Types.ObjectId,ref:"User",index:true},action:{type:String,required:true,index:true},module:{type:String,required:true,index:true},targetType:{type:String,trim:true,default:""},targetId:{type:Schema.Types.ObjectId,index:true},description:{type:String,trim:true,default:""},metadata:{type:Schema.Types.Mixed,default:{}}},{timestamps:true});
const categorySchema=new Schema({name:{type:String,required:true,unique:true,trim:true},slug:{type:String,required:true,unique:true},description:{type:String,default:""},isSystem:{type:Boolean,default:false},active:{type:Boolean,default:true}},{timestamps:true});
const productSchema=new Schema({name:{type:String,required:true,trim:true},sku:{type:String,required:true,unique:true,uppercase:true,trim:true},barcode:{type:String,unique:true,sparse:true,trim:true},categoryId:{type:Schema.Types.ObjectId,ref:"Category",required:true},manufacturer:{type:String,default:""},hsnCode:{type:String,trim:true,default:""},taxable:{type:Boolean,default:true},useDefaultGstRate:{type:Boolean,default:true},gstRate:{type:Number,min:0,max:100,default:null},gstExempt:{type:Boolean,default:false},gstPriceMode:{type:String,enum:["STORE","INCLUSIVE","EXCLUSIVE"],default:"STORE"},baseUnit:{type:String,enum:["ml","g","kg","tablets","pcs"],required:true},packageUnit:{type:String,enum:["ml","g","kg","tablets","pcs"],required:true},packageType:{type:String,required:true},packageSize:{type:Number,required:true,min:.0001},stockPackType:{type:String,enum:["Box","Carton"],default:"Box"},unitsPerStockPack:{type:Number,min:1,default:1},allowPackageSale:{type:Boolean,default:true},allowLooseSale:{type:Boolean,default:false},allowMixture:{type:Boolean,default:false},visibleInSales:{type:Boolean,default:true},packageSellingPrice:{type:Number,required:true,min:0},loosePricingMethod:{type:String,enum:["PROPORTIONAL","CUSTOM","TIERS","count_based"],default:"PROPORTIONAL"},looseUnit:{type:String,enum:["ml","g","kg","tablets","pcs","tablet","capsule","piece","sachet","other"],default:"ml"},loosePricePerUnit:{type:Number,min:0,default:0},looseConversionType:{type:String,enum:["fixed","count_on_open"],default:null},unitsPerPackage:{type:Number,min:1,default:null},priceTiers:[{quantity:{type:Number,min:.0001},price:{type:Number,min:0},_id:false}],reorderLevel:{type:Number,min:0,default:0},batchTracking:{type:Boolean,default:false},expiryTracking:{type:Boolean,default:false},wholesaleEnabled:{type:Boolean,default:false,index:true},wholesalePrice:{type:Number,min:0,default:0},wholesaleMinQty:{type:Number,min:1,default:1},wholesaleUnit:{type:String,enum:["Piece","Tablet","Bottle","Packet","Jar","Box","Carton"],default:"Box"},unitsPerWholesalePack:{type:Number,min:1,default:1},wholesalePriceTiers:[{quantity:{type:Number,min:1},price:{type:Number,min:0},_id:false}],allowWholesaleLooseSale:{type:Boolean,default:false},freeSchemeEnabled:{type:Boolean,default:false},freeSchemeType:{type:String,enum:["SAME_PRODUCT","DIFFERENT_PRODUCT"],default:"SAME_PRODUCT"},freeSchemeBuyQty:{type:Number,min:1,default:1},freeSchemeFreeQty:{type:Number,min:1,default:1},freeSchemeFreeProduct:{type:Schema.Types.ObjectId,ref:"Product",default:null},active:{type:Boolean,default:true}},{timestamps:true});
productSchema.add({wholesalePricingMethod:{type:String,enum:["FIXED","DISCOUNT_FROM_RETAIL"],default:"FIXED"},wholesaleDiscountPercent:{type:Number,min:0,max:100,default:0},wholesaleSaleUnit:{type:String,enum:["PACKAGE","WHOLESALE_PACK","LOOSE_UNIT"],default:"WHOLESALE_PACK"},wholesalePackEnabled:{type:Boolean,default:true},wholesalePackPrice:{type:Number,min:0,default:null},wholesaleLoosePrice:{type:Number,min:0,default:null}});
const batchSchema=new Schema({productId:{type:Schema.Types.ObjectId,ref:"Product",required:true,index:true},batchNumber:{type:String,default:"DEFAULT"},manufacturingDate:Date,expiryDate:Date,packageSize:{type:Number,required:true},sealedPackages:{type:Number,default:0,min:0},openQuantity:{type:Number,default:0,min:0},purchasePrice:{type:Number,default:0},sellingPrice:{type:Number,default:0},supplierId:{type:Schema.Types.ObjectId,ref:"Supplier"},status:{type:String,enum:["ACTIVE","EXHAUSTED","EXPIRED"],default:"ACTIVE"}},{timestamps:true});
batchSchema.virtual("totalBaseQuantity").get(function(){return this.sealedPackages*this.packageSize+this.openQuantity;});
const stockSchema=new Schema({productId:{type:Schema.Types.ObjectId,ref:"Product",required:true,index:true},batchId:{type:Schema.Types.ObjectId,ref:"InventoryBatch"},type:{type:String,required:true,index:true},baseQuantity:{type:Number,required:true},packageQuantity:{type:Number,default:0},looseQuantity:{type:Number,default:0},looseUnit:String,source:String,unit:String,direction:{type:String,enum:["IN","OUT"]},previousStock:Number,newStock:Number,referenceType:String,referenceId:Schema.Types.ObjectId,reason:String,note:String,actorId:{type:Schema.Types.ObjectId,ref:"User"}},{timestamps:true});
const settingsSchema=new Schema({key:{type:String,default:"global",unique:true},version:{type:Number,default:2},storeName:{type:String,default:"Oushadi"},store:{type:Schema.Types.Mixed,default:{}},invoice:{type:Schema.Types.Mixed,default:{}},receipt:{type:Schema.Types.Mixed,default:{}},checkout:{type:Schema.Types.Mixed,default:{}},discount:{type:Schema.Types.Mixed,default:{}},roundOff:{type:Schema.Types.Mixed,default:{}},gst:{type:Schema.Types.Mixed,default:{}},payments:{type:Schema.Types.Mixed,default:{}},inventory:{type:Schema.Types.Mixed,default:{}},batchExpiry:{type:Schema.Types.Mixed,default:{}},looseSales:{type:Schema.Types.Mixed,default:{}},customMix:{type:Schema.Types.Mixed,default:{}},purchases:{type:Schema.Types.Mixed,default:{}},expenses:{type:Schema.Types.Mixed,default:{}},customers:{type:Schema.Types.Mixed,default:{}},notifications:{type:Schema.Types.Mixed,default:{}},security:{type:Schema.Types.Mixed,default:{}},backup:{type:Schema.Types.Mixed,default:{}}},{timestamps:true,minimize:false});
const customerSchema=new Schema({name:{type:String,required:true,trim:true,index:true},phone:{type:String,trim:true,default:""},normalizedPhone:{type:String,trim:true,default:"",index:true},email:{type:String,trim:true,lowercase:true,default:"",index:true},address:{type:String,trim:true,default:""},status:{type:String,enum:["ACTIVE","INACTIVE"],default:"ACTIVE",index:true},active:{type:Boolean,default:true}},{timestamps:true});
const saleItemSchema=new Schema({kind:{type:String,enum:["PRODUCT","MIX"],default:"PRODUCT"},productId:{type:Schema.Types.ObjectId,ref:"Product"},name:{type:String,required:true},saleMode:{type:String,enum:["PACKAGE","LOOSE","MIX"],required:true},quantity:{type:Number,required:true},baseQuantity:{type:Number,default:0},baseUnit:String,unitPrice:{type:Number,required:true},total:{type:Number,required:true},packageType:String,hsnCode:{type:String,default:""},taxable:{type:Boolean,default:true},gstExempt:{type:Boolean,default:false},useDefaultGstRate:{type:Boolean,default:true},gstRate:{type:Number,default:0},gstPriceMode:{type:String,enum:["STORE","INCLUSIVE","EXCLUSIVE"],default:"STORE"},taxableValue:{type:Number,default:0},taxAmount:{type:Number,default:0},totalTax:{type:Number,default:0},cgst:{type:Number,default:0},sgst:{type:Number,default:0},igst:{type:Number,default:0},priceIncludesTax:{type:Boolean,default:false},ingredients:[{productId:{type:Schema.Types.ObjectId,ref:"Product"},name:String,baseQuantity:Number,baseUnit:String,unitPrice:Number,total:Number}]},{_id:false});
const paymentSchema=new Schema({method:{type:String,enum:["CASH","UPI","CARD","BANK"],required:true},amount:{type:Number,required:true,min:0},reference:{type:String,trim:true,default:""},paidAt:{type:Date,default:Date.now}},{_id:false});
const saleSchema=new Schema({invoiceNumber:{type:String,required:true,unique:true,index:true},customerType:{type:String,enum:["WALK_IN","EXISTING","NEW"],default:"EXISTING",index:true},customerId:{type:Schema.Types.ObjectId,ref:"Customer",default:null,index:true},customerSnapshot:{name:String,phone:String,email:String,address:String,doctorName:{type:String,trim:true,maxlength:120,default:""}},cashierSnapshot:{name:String,role:String},storeSnapshot:{name:String,legalName:String,address:String,phone:String,gstin:String,stateCode:String},items:{type:[saleItemSchema],required:true},subtotal:{type:Number,required:true,min:0},discount:{type:Number,default:0,min:0},taxableSubtotal:{type:Number,default:0,min:0},tax:{type:Number,default:0,min:0},cgst:{type:Number,default:0,min:0},sgst:{type:Number,default:0,min:0},igst:{type:Number,default:0,min:0},gstEnabled:{type:Boolean,default:false},gstPriceMode:{type:String,enum:["INCLUSIVE","EXCLUSIVE"],default:"INCLUSIVE"},gstCalculationMethod:{type:String,enum:["PRODUCT","CART"],default:"PRODUCT"},taxDetermination:{type:String,enum:["AUTOMATIC","INTRASTATE","INTERSTATE"],default:"AUTOMATIC"},taxType:{type:String,enum:["NONE","CGST_SGST","IGST"],default:"NONE"},showGstOnInvoice:{type:Boolean,default:true},gstDisplayStyle:{type:String,enum:["COMPACT","DETAILED"],default:"DETAILED"},supplierStateCode:{type:String,default:""},placeOfSupply:{type:String,default:""},roundOff:{type:Number,default:0},total:{type:Number,required:true,min:0},payments:{type:[paymentSchema],required:true},paymentStatus:{type:String,enum:["PAID","PARTIAL","UNPAID"],default:"PAID",index:true},amountPaid:{type:Number,default:0,min:0},balanceDue:{type:Number,default:0,min:0},actorId:{type:Schema.Types.ObjectId,ref:"User"}},{timestamps:true});
const supplierSchema=new Schema({name:{type:String,required:true,trim:true},code:{type:String,trim:true,default:"",index:true},phone:{type:String,trim:true,default:""},email:{type:String,trim:true,lowercase:true,default:""},address:{type:String,trim:true,default:""},taxNumber:{type:String,trim:true,default:""},active:{type:Boolean,default:true}},{timestamps:true});
const purchaseItemSchema=new Schema({
  productId:{type:Schema.Types.ObjectId,ref:"Product",required:true},
  productSnapshot:{name:String,sku:String,packageType:String,packageSize:Number,baseUnit:String},
  name:{type:String,required:true},batchNumber:{type:String,required:true},manufacturingDate:Date,expiryDate:Date,
  packageQuantity:{type:Number,required:true,min:1},freeQuantity:{type:Number,default:0,min:0},unitCost:{type:Number,required:true,min:0},total:{type:Number,required:true,min:0},
  hsnCode:{type:String,default:""},gstRate:{type:Number,default:0,min:0,max:100},gstPriceMode:{type:String,enum:["INCLUSIVE","EXCLUSIVE"],default:"INCLUSIVE"},taxType:{type:String,enum:["NONE","CGST_SGST","IGST"],default:"NONE"},taxableAmount:{type:Number,default:0,min:0},cgst:{type:Number,default:0,min:0},sgst:{type:Number,default:0,min:0},igst:{type:Number,default:0,min:0},totalGst:{type:Number,default:0,min:0},lineTotal:{type:Number,default:0,min:0},
},{_id:false});
const purchaseSchema=new Schema({
  purchaseNumber:{type:String,required:true,unique:true,index:true},supplierId:{type:Schema.Types.ObjectId,ref:"Supplier",required:true,index:true},
  supplierSnapshot:{name:String,phone:String,email:String,taxNumber:String},supplierInvoiceNumber:{type:String,trim:true,default:""},notes:{type:String,trim:true,default:""},
  items:{type:[purchaseItemSchema],required:true},subtotal:{type:Number,required:true,min:0},taxableAmount:{type:Number,default:0,min:0},totalGst:{type:Number,default:0,min:0},cgst:{type:Number,default:0,min:0},sgst:{type:Number,default:0,min:0},igst:{type:Number,default:0,min:0},taxType:{type:String,enum:["NONE","CGST_SGST","IGST"],default:"NONE"},supplierStateCode:{type:String,default:""},storeStateCode:{type:String,default:""},additionalCharges:{type:Number,default:0,min:0},discountType:{type:String,enum:["FIXED","PERCENTAGE"],default:"FIXED"},discountValue:{type:Number,default:0,min:0},discount:{type:Number,default:0,min:0},total:{type:Number,required:true,min:0},
  paymentStatus:{type:String,enum:["PAID","PARTIAL","UNPAID"],default:"PAID",index:true},paymentMethod:{type:String,enum:["CASH","UPI","CARD","BANK"],default:"CASH"},amountPaid:{type:Number,default:0,min:0},balanceDue:{type:Number,default:0,min:0},paymentReference:{type:String,trim:true,default:""},
  purchaseStatus:{type:String,enum:["DRAFT","RECEIVED","CANCELLED"],default:"RECEIVED",index:true},purchasedAt:{type:Date,default:Date.now,index:true},cancelledAt:Date,cancelledBy:{type:Schema.Types.ObjectId,ref:"User"},cancellationReason:{type:String,trim:true,default:""},actorId:{type:Schema.Types.ObjectId,ref:"User"},
},{timestamps:true});
const expenseSchema=new Schema({expenseNumber:{type:String,unique:true,sparse:true,index:true},title:{type:String,trim:true,default:""},categoryId:{type:Schema.Types.ObjectId,ref:"ExpenseCategory",index:true},category:{type:String,required:true,trim:true,index:true},description:{type:String,trim:true,default:""},paidTo:{type:String,trim:true,default:""},notes:{type:String,trim:true,default:""},amount:{type:Number,required:true,min:0},paidAmount:{type:Number,min:0},balanceDue:{type:Number,min:0},paymentMethod:{type:String,enum:["CASH","UPI","CARD","BANK"],required:true},paymentReference:{type:String,trim:true,default:""},expenseDate:{type:Date,default:Date.now,index:true},source:{type:String,enum:["MANUAL","PURCHASE"],default:"MANUAL",index:true},referenceType:String,referenceId:{type:Schema.Types.ObjectId,index:true},supplierId:{type:Schema.Types.ObjectId,ref:"Supplier"},staffId:{type:Schema.Types.ObjectId,ref:"User"},staffSnapshot:{name:String,email:String,role:String},actorId:{type:Schema.Types.ObjectId,ref:"User",index:true},creatorSnapshot:{name:String,role:String},editedBy:{type:Schema.Types.ObjectId,ref:"User"},status:{type:String,enum:["ACTIVE","VOID"],default:"ACTIVE",index:true},voidReason:{type:String,trim:true,default:""},voidedAt:Date,voidedBy:{type:Schema.Types.ObjectId,ref:"User"}},{timestamps:true});
const expenseCategorySchema=new Schema({name:{type:String,required:true,unique:true,trim:true},description:{type:String,trim:true,default:""},type:{type:String,enum:["MANUAL","SYSTEM"],default:"MANUAL"},active:{type:Boolean,default:true,index:true}},{timestamps:true});
const documentCounterSchema=new Schema({key:{type:String,required:true,unique:true,index:true},sequence:{type:Number,default:0,min:0}},{timestamps:true});
export const User=model("User",userSchema);
if(!User.schema.path("readNotificationIds"))User.schema.add({readNotificationIds:{type:[String],default:[]}});
if(!User.schema.path("dismissedNotificationIds"))User.schema.add({dismissedNotificationIds:{type:[String],default:[]}});
export const StaffRole=model("StaffRole",staffRoleSchema);
export const AuditLog=model("AuditLog",auditLogSchema);
export const Category=model("Category",categorySchema);
export const Product=model("Product",productSchema);
if(!Product.schema.path("barcodeType"))Product.schema.add({barcodeType:{type:String,enum:["EAN13","EAN8","UPCA","UPCE","CODE128","CODE39","QR"],default:"EAN13"}});
if(!Product.schema.path("stockPackType"))Product.schema.add({stockPackType:{type:String,enum:["Box","Carton"],default:"Box"},unitsPerStockPack:{type:Number,min:1,default:1}});
export const InventoryBatch=model("InventoryBatch",batchSchema);
export const StockTransaction=model("StockTransaction",stockSchema);
export const Settings=model("Settings",settingsSchema);
export const Customer=model("Customer",customerSchema);
Customer.schema.add({customerType:{type:String,enum:["RETAIL","WHOLESALE"],default:"RETAIL",index:true},businessName:{type:String,trim:true,default:""},gstin:{type:String,trim:true,uppercase:true,default:""},billingAddress:{type:String,trim:true,default:""},shippingAddress:{type:String,trim:true,default:""},creditLimit:{type:Number,min:0,default:0},outstandingAmount:{type:Number,min:0,default:0},defaultDiscount:{type:Number,min:0,max:100,default:0},notes:{type:String,trim:true,default:""}});
export const Sale=model("Sale",saleSchema);
Sale.schema.add({customerType:{type:String,enum:["WALK_IN","EXISTING","NEW"],default:"EXISTING",index:true}});
Sale.schema.add({cashierSnapshot:{name:String,role:String}});
Sale.schema.add({saleType:{type:String,enum:["SALE","WHOLESALE"],default:"SALE",index:true},wholesaleSummary:{paidQuantity:{type:Number,default:0},freeQuantity:{type:Number,default:0},totalOutgoing:{type:Number,default:0}}});
Sale.schema.add({"customerSnapshot.customerType":{type:String,enum:["RETAIL","WHOLESALE"],default:"RETAIL"},"customerSnapshot.businessName":{type:String,default:""},"customerSnapshot.gstin":{type:String,default:""},"customerSnapshot.billingAddress":{type:String,default:""},"customerSnapshot.shippingAddress":{type:String,default:""}});
Sale.schema.path("items").schema.add({wholesaleUnit:String,orderedQuantity:{type:Number,default:0},unitsPerWholesalePack:{type:Number,default:1},paidQuantity:{type:Number,default:0},freeQuantity:{type:Number,default:0},totalOutgoingQuantity:{type:Number,default:0},tierQuantity:{type:Number,default:0},schemeType:String,freeProductId:{type:Schema.Types.ObjectId,ref:"Product",default:null},freeProductName:String,manualFree:{type:Boolean,default:false},manualFreeReason:String});
Sale.schema.path("items").schema.path("saleMode").enum("WHOLESALE");
Sale.schema.path("customerId").required(false).default(null);
export const Supplier=model("Supplier",supplierSchema);
export const Purchase=model("Purchase",purchaseSchema);
export const Expense=model("Expense",expenseSchema);
Supplier.schema.add({code:{type:String,trim:true,default:"",index:true}});
Purchase.schema.add({notes:{type:String,trim:true,default:""},additionalCharges:{type:Number,default:0,min:0},discountType:{type:String,enum:["FIXED","PERCENTAGE"],default:"FIXED"},discountValue:{type:Number,default:0,min:0},discount:{type:Number,default:0,min:0},paymentStatus:{type:String,enum:["PAID","PARTIAL","UNPAID"],default:"PAID",index:true},amountPaid:{type:Number,default:0,min:0},balanceDue:{type:Number,default:0,min:0},purchaseStatus:{type:String,enum:["DRAFT","RECEIVED","CANCELLED"],default:"RECEIVED",index:true},cancelledAt:Date,cancelledBy:{type:Schema.Types.ObjectId,ref:"User"},cancellationReason:{type:String,trim:true,default:""}});
Purchase.schema.path("items").schema.add({productSnapshot:{name:String,sku:String,packageType:String,packageSize:Number,baseUnit:String},manufacturingDate:Date,freeQuantity:{type:Number,default:0,min:0}});
Expense.schema.add({expenseNumber:{type:String,unique:true,sparse:true,index:true},title:{type:String,trim:true,default:""},categoryId:{type:Schema.Types.ObjectId,ref:"ExpenseCategory",index:true},paidTo:{type:String,trim:true,default:""},notes:{type:String,trim:true,default:""},paidAmount:{type:Number,min:0},balanceDue:{type:Number,min:0},creatorSnapshot:{name:String,role:String},editedBy:{type:Schema.Types.ObjectId,ref:"User"},status:{type:String,enum:["ACTIVE","VOID"],default:"ACTIVE",index:true},voidReason:{type:String,trim:true,default:""},voidedAt:Date,voidedBy:{type:Schema.Types.ObjectId,ref:"User"}});
export const ExpenseCategory=model("ExpenseCategory",expenseCategorySchema);
ExpenseCategory.schema.add({description:{type:String,trim:true,default:""},type:{type:String,enum:["MANUAL","SYSTEM"],default:"MANUAL"}});
export const DocumentCounter=model("DocumentCounter",documentCounterSchema);
